/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorsNoteRouteImport } from './routes/authors-note'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SupplyRouteImport } from './routes/supply'
import { Route as TimingRouteImport } from './routes/timing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsNoteRoute = AuthorsNoteRouteImport.update({
  id: '/authors-note',
  path: '/authors-note',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyRoute = SupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const TimingRoute = TimingRouteImport.update({
  id: '/timing',
  path: '/timing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authors-note': typeof AuthorsNoteRoute
  '/receipts': typeof ReceiptsRoute
  '/sources': typeof SourcesRoute
  '/supply': typeof SupplyRoute
  '/timing': typeof TimingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authors-note': typeof AuthorsNoteRoute
  '/receipts': typeof ReceiptsRoute
  '/sources': typeof SourcesRoute
  '/supply': typeof SupplyRoute
  '/timing': typeof TimingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authors-note': typeof AuthorsNoteRoute
  '/receipts': typeof ReceiptsRoute
  '/sources': typeof SourcesRoute
  '/supply': typeof SupplyRoute
  '/timing': typeof TimingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/authors-note' | '/receipts' | '/sources' | '/supply' | '/timing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authors-note' | '/receipts' | '/sources' | '/supply' | '/timing'
  id:
    | '__root__'
    | '/'
    | '/authors-note'
    | '/receipts'
    | '/sources'
    | '/supply'
    | '/timing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsNoteRoute: typeof AuthorsNoteRoute
  ReceiptsRoute: typeof ReceiptsRoute
  SourcesRoute: typeof SourcesRoute
  SupplyRoute: typeof SupplyRoute
  TimingRoute: typeof TimingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors-note': {
      id: '/authors-note'
      path: '/authors-note'
      fullPath: '/authors-note'
      preLoaderRoute: typeof AuthorsNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply': {
      id: '/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof SupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timing': {
      id: '/timing'
      path: '/timing'
      fullPath: '/timing'
      preLoaderRoute: typeof TimingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsNoteRoute: AuthorsNoteRoute,
  ReceiptsRoute: ReceiptsRoute,
  SourcesRoute: SourcesRoute,
  SupplyRoute: SupplyRoute,
  TimingRoute: TimingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
